// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpoilerFreeHighlights.Core.Persistence;

#nullable disable

namespace SpoilerFreeHighlights.Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SpoilerFreeHighlights.Shared.Models.Game", b =>
                {
                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("AwayTeamId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("HomeTeamId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsHypothetical")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDateLeagueTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("YouTubeLink")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("LeagueId", "Id");

                    b.HasIndex("LeagueId", "AwayTeamId");

                    b.HasIndex("LeagueId", "HomeTeamId");

                    b.ToTable("Games");
                });

            modelBuilder.Entity("SpoilerFreeHighlights.Shared.Models.League", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.ToTable("Leagues");
                });

            modelBuilder.Entity("SpoilerFreeHighlights.Shared.Models.LeagueConfiguration", b =>
                {
                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<string>("SelectPlaylistType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("LeagueId");

                    b.ToTable("LeagueConfigurations");
                });

            modelBuilder.Entity("SpoilerFreeHighlights.Shared.Models.PlaylistConfiguration", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("LeagueConfigurationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("RequiredVideoPartMatches")
                        .HasColumnType("int");

                    b.Property<int>("RequiredVideoTitlePercentageMatch")
                        .HasColumnType("int");

                    b.Property<string>("TitlePattern")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.HasKey("Id");

                    b.HasIndex("LeagueConfigurationId");

                    b.ToTable("PlaylistConfigurations");
                });

            modelBuilder.Entity("SpoilerFreeHighlights.Shared.Models.Team", b =>
                {
                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("LogoLink")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("LeagueId", "Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("SpoilerFreeHighlights.Shared.Models.VideoTitleDateFormat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PlaylistConfigurationId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistConfigurationId");

                    b.ToTable("VideoTitleDateFormats");
                });

            modelBuilder.Entity("SpoilerFreeHighlights.Shared.Models.VideoTitleIdentifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PlaylistConfigurationId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistConfigurationId");

                    b.ToTable("VideoTitleIdentifiers");
                });

            modelBuilder.Entity("SpoilerFreeHighlights.Shared.Models.VideoTitleTeamFormat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PlaylistConfigurationId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistConfigurationId");

                    b.ToTable("VideoTitleTeamFormats");
                });

            modelBuilder.Entity("SpoilerFreeHighlights.Shared.Models.YouTubePlaylist", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("LeagueId");

                    b.ToTable("YouTubePlaylists");
                });

            modelBuilder.Entity("SpoilerFreeHighlights.Shared.Models.YouTubeVideo", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateOnly?>("ExtractedTitleDate")
                        .HasColumnType("date");

                    b.Property<string>("ExtractedTitleIdentifierA")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ExtractedTitleIdentifierB")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ExtractedTitleTeamA")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ExtractedTitleTeamB")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PlaylistId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("PublishedDateTimeLeague")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PublishedDateUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistId");

                    b.ToTable("YouTubeVideos");
                });

            modelBuilder.Entity("SpoilerFreeHighlights.Shared.Models.Game", b =>
                {
                    b.HasOne("SpoilerFreeHighlights.Shared.Models.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SpoilerFreeHighlights.Shared.Models.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("LeagueId", "AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SpoilerFreeHighlights.Shared.Models.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("LeagueId", "HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("League");
                });

            modelBuilder.Entity("SpoilerFreeHighlights.Shared.Models.LeagueConfiguration", b =>
                {
                    b.HasOne("SpoilerFreeHighlights.Shared.Models.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("SpoilerFreeHighlights.Shared.Models.PlaylistConfiguration", b =>
                {
                    b.HasOne("SpoilerFreeHighlights.Shared.Models.LeagueConfiguration", null)
                        .WithMany("Playlists")
                        .HasForeignKey("LeagueConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpoilerFreeHighlights.Shared.Models.Team", b =>
                {
                    b.HasOne("SpoilerFreeHighlights.Shared.Models.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("SpoilerFreeHighlights.Shared.Models.VideoTitleDateFormat", b =>
                {
                    b.HasOne("SpoilerFreeHighlights.Shared.Models.PlaylistConfiguration", null)
                        .WithMany("DateFormats")
                        .HasForeignKey("PlaylistConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpoilerFreeHighlights.Shared.Models.VideoTitleIdentifier", b =>
                {
                    b.HasOne("SpoilerFreeHighlights.Shared.Models.PlaylistConfiguration", null)
                        .WithMany("TitleIdentifiers")
                        .HasForeignKey("PlaylistConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpoilerFreeHighlights.Shared.Models.VideoTitleTeamFormat", b =>
                {
                    b.HasOne("SpoilerFreeHighlights.Shared.Models.PlaylistConfiguration", null)
                        .WithMany("TeamFormats")
                        .HasForeignKey("PlaylistConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SpoilerFreeHighlights.Shared.Models.YouTubePlaylist", b =>
                {
                    b.HasOne("SpoilerFreeHighlights.Shared.Models.League", "League")
                        .WithMany()
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("League");
                });

            modelBuilder.Entity("SpoilerFreeHighlights.Shared.Models.YouTubeVideo", b =>
                {
                    b.HasOne("SpoilerFreeHighlights.Shared.Models.YouTubePlaylist", "Playlist")
                        .WithMany("Videos")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");
                });

            modelBuilder.Entity("SpoilerFreeHighlights.Shared.Models.LeagueConfiguration", b =>
                {
                    b.Navigation("Playlists");
                });

            modelBuilder.Entity("SpoilerFreeHighlights.Shared.Models.PlaylistConfiguration", b =>
                {
                    b.Navigation("DateFormats");

                    b.Navigation("TeamFormats");

                    b.Navigation("TitleIdentifiers");
                });

            modelBuilder.Entity("SpoilerFreeHighlights.Shared.Models.YouTubePlaylist", b =>
                {
                    b.Navigation("Videos");
                });
#pragma warning restore 612, 618
        }
    }
}
