global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.Configuration;
global using Serilog;
global using ILogger = Serilog.ILogger;
global using SpoilerFreeHighlights.Core.Models;
global using SpoilerFreeHighlights.Core.Persistence;
global using SpoilerFreeHighlights.Core.Services;
global using SpoilerFreeHighlights.Core.Services.LeagueServices;
global using SpoilerFreeHighlights.Shared.Enums;
global using SpoilerFreeHighlights.Shared.Models;
global using SpoilerFreeHighlights.Shared.Utility;
